project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-W3PRTJPWHR"
  favicon: "favicon.png"
  sidebar:
    title: "Research Methods"
    text: "Research Methods Resources"
    style: "floating"
    search: true
    contents:
      - section: "Getting Started"
        contents: 
          - methodsoverview.qmd
      - section: "Statistical Software"
        contents:
          - software.qmd
          - introR.qmd
      - section: "Experimental"
        contents:
          - experimental.qmd
      - section: "Non-Experimental"
        contents:
          - nonexperimental.qmd
      - section: "Advanced Methods"
        contents:
          - sem.qmd
          - advancedmeasurement.qmd
      - section: "Modern Missing Data Methods"
        contents:
          - fiml.qmd
          - multipleimputation.qmd
  navbar:
    logo: thinker_round.png
    left:
      - href: index.qmd
        text: Home
      - text: "Project Based Notebooks"
        href: notebooks.qmd
      - courses.qmd
      - href: about.qmd
        text: "About"        
        
    right:
      - icon: github
        href: https://github.com/auqmer/statistical-thinking
        
  page-footer:
    border: false
    left: "William Murrah, 2023"
    right:
      - icon: github
        href: https://github.com/wmmurrah
format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css
    toc: true

editor: source