---
title: "About Me"
urlcolor: blue
description: |
  Some additional details about me and my research.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Dr. William (Hank) Murrah, Ph.D.

As an educational researcher, Dr. Murrah focuses on understanding how people learn to think. His work falls into three main areas: (1) studying the skills children need to succeed in school; (2) developing interventions that address resource disparities important for learning; (3) developing methods to understand the impact of social and contextual factors on learning, motivation, and achievement.
He is co-founder of the Quantitative Methods in Educational Research learning community, which is dedicated to supporting the growth and development of graduate students. A major goal of his when working with graduate students is to provide experiences with empirical research that helps them to stand out as scholars by providing skills needed to succeed as modern educational researchers. 