---
title: "Courses"
---

### Experimental Design (ERMA 7300)

#### Visualizing and Describing Data

-   Exploring Data Graphically - [Tutorial](https://auqmer.github.io/statistical-thinking/posts/2020-09-08-exploring-data-graphically/) [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=7d27afac-a19c-4df3-823c-ac30011ffccc)

-   Measures of Central Tendency - [Tutorial](https://auqmer.github.io/statistical-thinking/posts/2020-09-16-central-tendency/) [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8d53677e-f7e5-4c52-88e8-ac2f0133d380)

-   Measures of Variability - [Tutorial](https://auqmer.github.io/statistical-thinking/posts/2020-09-23-variability/) [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=cad74732-e286-45be-8388-ac2f0144260b)

### Linear Modeling (ERMA 7310)

#### Foundations of Modeling

-   Introduction to R and RStudio - [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=630b1601-916c-43b2-8315-ad8f016cda3e)
-   File Folders and Navigation [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=48773598-f6ba-4771-8515-ad880135ee36)

### Structural Equation Modeling (ERMA 8340)

#### Foundations of Structural Equation Modeling

-   Introduction to Structural Equation Modeling

-   Regression Fundamentals

    -   Preparing SPSS data for Mplus - [Tutorial](https://auqmer.github.io/statistical-thinking/posts/2019-01-13-prepare-spss-data-for-mplus/)
    -   Preparing R data for Mplus - [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=af0df7b4-a9b5-42ad-afbc-acb600081154)

-   Modeling and Hypothesis Testing

    -   Hypothesis Testing [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=da5f16e0-0d76-47bc-ae11-acb5013ecf71)
    -   Bootstrapping [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c78c1561-d1c4-45d7-b32d-acb600035b78)

-   Model Specification - Path Analysis

    -   Path Specification [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c81e249b-a582-48f5-ac3f-acba01394841)
    -   Path Identification [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=22901e97-0c76-4455-b449-acba014708b0)
    -   Using Mplus Diagrammer [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=cbbebdc0-9d6b-4cba-8701-acba01597164)
    -   Using Onyx to diagram [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4455b63f-81c5-4ee4-99f3-acbc016617fe)

-   Graph Theory

    -   DAG Basics [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d3f0dc2d-90ff-4426-8326-acc1012f38ec)
    -   Diagramming Causal Graphs [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=afd52f85-d7a7-4bca-ba9f-acba01509e6e)\
    -   Thinking Clearly [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d18e317d-29d3-41bc-a2bf-acc3012ee1eb)

-   Model Specification - CFA [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=551e64d9-979b-4e75-a62b-acc80145e8a4)

-   Model Specification - SEM

    -   Specification [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=cf0aa371-3c6b-468e-a2a8-accf01875b14)
    -   Demonstration [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=64d5faa8-bf06-4903-b922-accf0189cc14)

-   Model Analysis - Local Fit

    -   Estimation Methods [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=eb6256a9-42fe-46ee-b015-ab8201425373)
    -   Standardization and Path Analysis [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fed1886a-cfa8-48eb-b58e-ab82014888d2)

-   Model Analysis - Global Fit

    -   Global Fit Theory [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9e9f6a28-7a54-443e-afde-ab890112cf50)
    -   Global Fit Demonstration [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=2f69e5b0-fe89-4472-b3ab-ab8c01449535)

-   Model Analysis - CFA

    -   CFA Analysis [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1ab511d1-ad58-47f8-a057-ab8f0135d932)
    -   CFA Analysis Demonstration [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=063488fc-e110-47ce-b32c-ab900130465a)

-   Model Analysis - SEM [Video](https://auburn.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=2c402a8d-2433-449a-a5d8-ab97011b6bad)

### Multilevel Modeling (ERMA Special Topics)

### Advanced Psychometrics (ERMA 8350)
